### ISSUE TITLE
Properties modules bug

### ISSUE THREAD

**Issue by juliettelavoie** [Ouranosinc/xsdba#168]
### Setup Information

- xsdba version: 0.4
- Python version: 3.12
- Operating System: linux

### Description

When properties were in xclim, I was able to use `xc.build_indicator_module_from_yaml` to build a module out of the xsdba properties. Since the separation, the properties are no longer in the registry.

Is there a way to add them to the registry or to do an xsdba version of `xc.build_indicator_module_from_yaml` ?

What is the best way to do this ? @aulemahal @coxipi 

### Steps To Reproduce

properties.yml:
```
realm: generic
indicators:
  mean-tasmax:
    base: xsdba.properties.mean
    cf_attrs:
      long_name: Mean maximum temperature
      standard_name: air_temperature
    input:
      da: tasmax
```
```
xc.build_indicator_module_from_yaml('properties.yml')
```
gives:
```
ValueError: Constructing mean-tasmax failed with ValueError('Requested base class xsdba.properties.mean is neither in the indicators registry nor in base classes registry.')
```

### Additional context

this is being used in `xs.properties_and_measures`

### Contribution

- [ ] I would be willing/able to open a Pull Request to address this bug.
